FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  designappproj.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/designappproj.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  designappproj.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/designappproj.py
FROM python
RUN pip install flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  designappproj.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/designappproj.py
